# Miscellaneous testing

In [1]:
import torch

In [2]:
predicted = torch.tensor(
    [[0.0819, 0.0494, 0.0697, 0.0646, 0.0677, 0.0576, 0.0603, 0.0496, 0.0712, 0.0793, 0.0688, 0.0827, 0.0722, 0.0583, 0.0667],
    [0.0819, 0.0494, 0.0697, 0.0646, 0.0677, 0.0576, 0.0603, 0.0496, 0.0712, 0.0793, 0.0688, 0.0827, 0.0722, 0.0583, 0.0667],
    [0.0819, 0.0494, 0.0697, 0.0646, 0.0677, 0.0576, 0.0603, 0.0496, 0.0712, 0.0793, 0.0688, 0.0827, 0.0722, 0.0583, 0.0667]]
)

In [6]:
predicted = torch.tensor(
    [[0.01, 0.05, 0.02, 0.02, 0.9],
    [0.03, 0.1,  0.42, 0.05, 0.4 ]]
)

In [3]:
actual = torch.tensor(
    [[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
    [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
    [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]]
)

In [8]:
actual = torch.tensor(
    [4, 2]
)

In [10]:
from torch.nn.functional import cross_entropy

In [53]:
cross_entropy_custom = lambda p, q: - torch.sum(p * torch.log(q), axis=1)

In [34]:
actual[:1]

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [52]:
cross_entropy_custom(actual[2:3], predicted[2:3])

tensor([1.2197])

In [16]:
actual[:1]

tensor([4])

In [17]:
predicted[:1]

tensor([[0.0100, 0.0500, 0.0200, 0.0200, 0.9000]])

In [15]:
cross_entropy(predicted[:1], actual[:1])

tensor(0.9812)

In [2]:
from gymnasium.wrappers.flatten_observation import FlattenObservation
from footsies_gym.envs.footsies import FootsiesEnv
from footsies_gym.wrappers.normalization import FootsiesNormalized
from footsies_gym.wrappers.action_comb_disc import FootsiesActionCombinationsDiscretized

In [3]:
env = FootsiesActionCombinationsDiscretized(
    FlattenObservation(
        FootsiesNormalized(
            FootsiesEnv()
        )
    )
)

In [4]:
from main import import_agent, load_agent_model

In [6]:
agent = import_agent("mimic", env, {})

In [7]:
load_agent_model(agent, "mimic")

Agent loaded


In [8]:
from agents.mimic.agent import FootsiesAgent as MimicAgent

In [9]:
agent: MimicAgent

In [13]:
agent.p1_model.network.layers

Sequential(
  (0): Linear(in_features=36, out_features=32, bias=True)
  (1): Linear(in_features=32, out_features=15, bias=True)
  (2): InputClip()
  (3): DebugStoreRecent()
  (4): Sigmoid()
  (5): DebugStoreRecent()
)

In [14]:
import torch
from torch import nn

In [17]:
class SimpleNN(nn.Module):
    def __init__(self, i, o):
        super().__init__()
        self.layers = nn.Sequential(
            nn.Linear(i, 4),
            nn.Linear(4, o),
        )
    
    def forward(self, x):
        return self.layers(x)

In [18]:
n = SimpleNN(8, 8)

In [25]:
n.requires_grad_(False)

SimpleNN(
  (layers): Sequential(
    (0): Linear(in_features=8, out_features=4, bias=True)
    (1): Linear(in_features=4, out_features=8, bias=True)
  )
)

In [23]:
x = torch.rand((1, 8))

In [26]:
n(x)

tensor([[-0.0357,  0.2117,  0.2518, -0.2706,  0.3531, -0.1332,  0.1393, -0.2218]])

In [27]:
n(n(x))

tensor([[ 0.0164,  0.2976,  0.3487, -0.2301,  0.2922, -0.1116,  0.3216, -0.2168]])

In [32]:
n.layers[0].weight.shape

torch.Size([4, 8])

In [51]:
w0 = n.layers[0].weight
w1 = n.layers[1].weight
b0 = n.layers[0].bias.unsqueeze(dim=1)
b1 = n.layers[1].bias.unsqueeze(dim=1)

In [53]:
w1 @ (w0 @ x.T + b0) + b1

tensor([[-0.0357],
        [ 0.2117],
        [ 0.2518],
        [-0.2706],
        [ 0.3531],
        [-0.1332],
        [ 0.1393],
        [-0.2218]])

In [55]:
w1 @ w0 @ x.T + w1 @ b0 + b1

tensor([[-0.0357],
        [ 0.2117],
        [ 0.2518],
        [-0.2706],
        [ 0.3531],
        [-0.1332],
        [ 0.1393],
        [-0.2218]])